apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mcp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mcp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
